### ISSUE TITLE
How to implement EventSource on a route

### ISSUE THREAD

**Issue by apparentvisuals** [unjs/h3#244]
Currently doing a simple EventSource endpoint by doing the following
```
const headers = {
  'Content-Type': 'text/event-stream',
  'Connection': 'keep-alive',
  'Cache-Control': 'no-cache'
};
res.writeHead(200, headers);
res.write('data: test\n\n');

req.on('close', () => {
  // remove res from list
});
```

This works but I always end up with an error from h3 `[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

**Comment by ENBYSS** [comment]
The thing I found is that the error is happening because the request is kept open after the response is technically finished. When I tried this in Nuxt3, I kept getting the error as well - specifically when using `writeHead`. However, any other way of setting the headers from what I found - while removing the error - would also instantly close the connection.

I'd say experiment with using alternatives to `writeHead` - like `setHeader` - and check when `req.on('close', ...)` triggers. If it closes it immediately it will be logged - if it doesn't, close the client and see if it logs the disconnect. In my experience it doesn't, but maybe that's a Nuxt3 thing.

**Comment by fabianwohlfart** [comment]
Having the same question.
What to do to remove the Error Message?

**Comment by Hebilicious** [comment]
@fabianwohlfart Apologies for the late answer. Could you try returning `null` as well ?
We should document this.

**Comment by hazadus** [comment]
@apparentvisuals try using @Atinux gist, it works for me very well!
https://gist.github.com/Atinux/05836469acca9649fa2b9e865df898a2

**Comment by pi0** [comment]
Hi. Going to work on a built-in utility for supporting server-sent events. Please track via #477
