### ISSUE TITLE
Benchmark against other webservers

### ISSUE THREAD

**Issue by Attacler** [unjs/h3#293]
### Describe the feature

Is H3 faster than other webserver libraries like ExpressJS/Fastify?
Did some one do benchmarks on them?

It would be nice to have a comparison between alteast those 3.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi dear @Attacler. It probably is or at last has almost identical RPS performance. 

I rather not to compare bare h3 with other frameworks because main goals of h3 are scalable performance by using composable utility architecture and portability. Often, you can see main benefits by using h3 in a real world scenario and the bare benchmarks are not even close to that because main logic is user code not framework.

checkout this for a comparison: https://github.com/fastify/benchmarks/


Also PR welcome to add a perf section to the docs with above explanations:)

**Comment by Attacler** [comment]
I totaly agree, i didnt knew that Fastify had a benchmarkings repo.
Thank you for your answer!

**Comment by jbergstroem** [comment]
It could be interesting to compare how much it adds to a baseline, similar to this repository: https://github.com/TigersWay/cloudflare-playground
