### ISSUE TITLE
h3 appendHeader function makes case sensitive headers lowercase

### ISSUE THREAD

**Issue by ThomasBerne** [unjs/h3#335]
### Environment

Nuxt 3.2.0.

Create an endpoint like so:

```typescript
export default createApp({
  debug: true,
})
  .use(
    defineEventHandler((event) => {
      appendHeader(event, 'Access-Control-Allow-Origin', 'test');
    }),
  )
  .use('/', () => 'hello world').handler;
```

### Reproduction

![image](https://user-images.githubusercontent.com/23033483/219310316-4f03eed5-f0de-40d7-9435-cbe2e6dd7fa3.png)

![image](https://user-images.githubusercontent.com/23033483/219310363-2b668c48-ed49-47e1-b8c4-6ea92e1b6336.png)

### Describe the bug

The h3 function appendHeader makes the headers lowercase and as they are case sensitive, they don't work.

**Comment by ThomasBerne** [comment]
appendHeaders has the same problem:

```typescript
appendHeaders(event, 
  {
    'Access-Control-Allow-Origin':'test',
  }
);
```

**Comment by NozomuIkuta** [comment]
HTTP headers names (i.e. HTTP field names) are supposed to be case-insensitive ([ref](https://www.rfc-editor.org/rfc/rfc9110#section-5.1)).

Actually, `appendHeaders` and `appendHeader` utilities are wrapper of [Nodejs' `http.ServerResponse.setHeader`](https://nodejs.org/api/http.html#responsesetheadername-value), so it's Nodejs' native behavior.

https://github.com/unjs/h3/blob/a0e21c11c5bc9c219fa27fc531d690548926b12b/src/node.ts#L1-L4

https://github.com/unjs/h3/blob/0979caca040ac2738f70a374771bb751434bda9d/src/event/event.ts#L6-L14

https://github.com/unjs/h3/blob/0979caca040ac2738f70a374771bb751434bda9d/src/utils/response.ts#L116-L135

If your app doesn't work due to case-changed HTTP header name, it might be that a part of your infrastructure (e.g. server-side app) is case-sensitive about HTTP header. 🤔
Or, are you using some 3rd-party cloud service?

**Comment by ThomasBerne** [comment]
Maybe I'm testing it wrong. I'll try something. Thank you for your information. Always thought they were case sensitive. I tried your package also. Thanks for your work on it :)
