### ISSUE TITLE
When I use useSession, I wanna store my session in Redis.

### ISSUE THREAD

**Issue by moyukingS** [unjs/h3#379]
### Describe the feature

I tried using nuxt-session for session management, but unfortunately it doesn't work in middleware. So I switched to useSession, but it lacks the option to store data.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
@pi0  We could provide a way to integrate h3 with unstorage to support all drivers at once

**Comment by pi0** [comment]
Hi, dear @moyukingS. This is by the design of how useSession works. It encrypts all session into a barrier format into the cookies. This way we don't need any external storage while can preserve data.

There is a case that you might want to store/retrieve additional session data from an external storage. There is no problem you can easily use the built-in added `id` to do this.

Here is an example how you can load session from an external source (could be unstorage, database, memory object, etc)

https://stackblitz.com/edit/github-fb8ren?file=app.ts&startScript=dev

**Comment by martinszeltins** [comment]
@pi0  There is one problem with using external storage to fetch session data because it does not have automatic garbage collection which means that old session data stored in external storage will not get automatically deleted when session cookie expires. The old session data will take up a lot of space as time goes on.

That means I either need to run a cron job to periodically delete old / expired session data (which sucks) or I wonder if there is a solution already available for such use case.

**Comment by oom-** [comment]
@martinszeltins 
> @pi0 There is one problem with using external storage to fetch session data because it does not have automatic garbage collection which means that old session data stored in external storage will not get automatically deleted when session cookie expires. The old session data will take up a lot of space as time goes on.
> 
> That means I either need to run a cron job to periodically delete old / expired session data (which sucks) or I wonder if there is a solution already available for such use case.

You can setup expiration in Redis to do that automatically.


@pi0 
> Hi, dear @moyukingS. This is by the design of how useSession works. It encrypts all session into a barrier format into the cookies. This way we don't need any external storage while can preserve data.
> 
> There is a case that you might want to store/retrieve additional session data from an external storage instead of encrypted cookies. There is no problem you can easily use the built-in added `id` to do this.
> 
> Here is an example how you can load session from an external source (could be unstorage, database, memory object, etc)
> 
> https://stackblitz.com/edit/github-fb8ren?file=app.ts&startScript=dev

Sorry but the goal to store it in a Redis is to : 1 never send the data (even encrypted) to the client + have all sessions still alive when you restart your Nuxt instance.

Would it be nice to have like a useSessionStorage function allowing to handle all storage ? as express is doing it ?

**Comment by martinszeltins** [comment]
> You can setup expiration in Redis to do that automatically.

Ah, yes that is true. That helps a lot. But there still seems to be missing a good session management feature in frontend frameworks like Nuxt. You need to code it yourself if you need sessions.

For me, I had to create the following all by hand because I did not find an existing solution for this.

In a Nuxt 3 project.

1. When user logs in, a unique session id is generated and stored in a cookie (using cryptography and secret key).
2. When data related to user session changes, it triggers a persist to Redis in the background and handles race conditions.
3. When app is loaded, during SSR, it looks up user session by session id (if cookie exists) and retrieves all user session data from Redis and puts it back in pinia store.

There is a lot that goes into creating session management manually. You need to consider security, serialization, expiration, persistence, race conditions, loading session data etc. I wish Nuxt had a good out-of-the-box solution for this common use case.

**Comment by cjpearson** [comment]
This is an old issue, but I wanted to share [our solution](https://www.npmjs.com/package/@scayle/h3-session) in case it's useful for anyone else. As we were upgrading sites built on Nuxt 2 and express-session we needed something compatible for a smooth migration.
