### ISSUE TITLE
sendStream(event, data) throws an error (data.pipe is not a function)

### ISSUE THREAD

**Issue by cosbgn** [unjs/h3#399]
### Environment

localhost

### Reproduction

```js
const headers = {"Authorization": `Bearer ${process.env.OPENAI_KEY}`}
export default defineEventHandler(async (event) => {
	let model = "gpt-3.5-turbo"
	let messages = [{content:"Where is Rome", role:"user"}]
	const r = await $fetch("https://api.openai.com/v1/chat/completions", {method:"POST", headers, body:{ model, messages, stream:true }, responseType: "stream"})
	console.log(r) // ReadableStream { locked: false, state: 'readable', supportsBYOB: false } 
	return sendStream(event, r)	
})
```

### Describe the bug

The code above used to work, and now it throws `data.pipe` - I did update nuxt with --force so it might be cause by an update to h3

**Comment by cosbgn** [comment]
I think it might be an issue with the api as the library works

**Comment by joseph-montanez** [comment]
This is because Nuxt 3 keeps upping H3 dependency. Prior to the official Nuxt 3 final release it was H3 V0.x. (base on a sub-component), then that sub-component bumped that to H3 V1.0. Then as of Nuxt 3.5, its pinned H3 V1.6.6 which changed how sendStream uses event.res to event.node.res which now full expects a writable stream and cannot piggy back of a `ReadableStream`.

Its annoying to change this for the 3rd time since using Nuxt 3, but here is my work around:

```Typescript
import {PassThrough} from "stream";

export default defineEventHandler(async (event: H3Event) => {
    const response = new PassThrough();
    //-- Logic here
    someFunc(() => {
        //
        event.node.res.write(JSON.stringify({
            success: true,
            message: '',
        }));
        event.node.res.end();
    });
    return sendStream(event, response);
});
```

I am assuming H3 V1.6.6 change was a breaking change. This is mainly because `ReadableStream` not a writeable stream, it needs to implement `pipe`. `ReadableStream` does not implement `pipe`, rather `pipeTo`. I am sure there is a more elegant way to handle this, but this is what I am using for now, for async responses.

**Comment by manuel-84** [comment]
thx @joseph-montanez  you gave me the idea:

```js
import { sendStream } from 'h3'
import { PassThrough } from 'stream'

export default defineEventHandler(async (event) => {
 // -- rest of the code --
  const stream = new PassThrough()
  const streamingModel = new ChatOpenAI({
    streaming: true,
    callbacks: [
      {
        handleLLMNewToken(token) {
          stream.write(token)
        },
        handleLLMEnd() {
          stream.end()
        }
      }
    ]
  })
  // -- rest of the code --
  return sendStream(event, stream)
})
```
