### ISSUE TITLE
Missing next function in defineEventHandler(event)

### ISSUE THREAD

**Issue by harrytran998** [unjs/h3#501]
### Describe the feature

Hi Nuxt team, thank you for your awesome libs 🌟 I fall in love with the Unjs so I decide to move all our backends from https://hono.dev to the Nuxt server with h3. 

But we have some problems with middleware! We consume some middleware like Compression, Timing, or Etag(code in https://github.com/honojs/hono/blob/main/src/middleware/compress/index.ts) of Hono. 

Hono exposes the next function - Mean executed the api route --> Do something

```ts
return async (ctx, next) => {
    await next() -------->>> Execute API route
	⬇️ then compress data --> Return to client

    const accepted = ctx.req.headers.get('Accept-Encoding')
    const pattern = options?.encoding ?? /gzip|deflate/
    const match = accepted?.match(pattern)
    if (!accepted || !match || !ctx.res.body) {
      return
    }
    const encoding = match[0]
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    const stream = new CompressionStream(encoding as EncodingType)
    ctx.res = new Response(ctx.res.body.pipeThrough(stream), ctx.res)
    ctx.res.headers.set('Content-Encoding', encoding)
  }
  ```

Can h3 do this 🤔. Or you can give me some hint to do this with h3?

Thank you!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the kind word dear @harrytran998 and also for raising this question.

H3 has no support for `next()` API in order to differ for the response to be modified but instead of >=1.8 we have introduced two new options (global `onBeforeResponse`) and event handler with object syntax with `after: []` hooks). Using two API, you can elegantly make your own response handler to add Compression or other transformations.

I have made you a simple example to get an idea how it works (please take note that, stackblitz does not supports compression. you need to run example locally) 

https://stackblitz.com/edit/github-mb6bz3?file=app.ts&startScript=dev


Please let me know how you feel about these two APIs and if they seem a good replacement for you. I personally prefer the simplicity of this hooks and see them more readable than `await next()` which is kinda hard to read at first glance and also would add to the runtime overhead and performance if we add it to the h3 core but open to discussions 👍🏼

**Comment by harrytran998** [comment]
Wow - thank you for the quick response! 

1. I think the naming of the function `after` should be consistent with `onBeforeResponse` on `createApp` - This will lead the document to be easier to read and memorize with the end-user. Or at least will be `onAfter` to mark this as a callback event 😆.

```ts
app.use(
  eventHandler({
    after: [compressResponse],
    handler: (event) => {
      return 'Hello World!';
    },
  })
);
```

2. Can you explain why `onBeforeResponse` is a function, but the `before` is an array function 😆. I think if we design the API following the composition --> `onBeforeResponse` should be an array too 🤔.


3. What if I want to order add middleware onBeforeResponse if we had `onBeforeResponse` on createApp, and some middleware in the `eventHandler`  function 🤔. 

Like, in some of the API routes, I want to add some additional headers on the 1st middleware in the `eventHandler`, and `onBeforeResponse` in the `createApp` receive those headers, and do some conditioning work.

**Comment by pi0** [comment]
The order is: `global.onRequest` > (`handler.before[]` > `handler` > `handler.after[]`) > `global.onBeforeResponse` > `global.onAfterResponse`. 

I think that non-array mode should be supported for even object syntax also noticed the same DX inconsistency issue 👍🏼 Naming consistency is also valid point let me propose a PR.

The reason that global one is not array is that it is an advanced API and for maximum performance, kept simple. frameworks such as Nitro use https://hookable.unjs.io to support multiple hooks). Still up to consider supporting array if you have valid usecases not possible with current API.

**Comment by harrytran998** [comment]
Thank you for your quick response! 
I think currently to maximize the performance, keeping simple global is fine! Although object or array, I guess the current API work well with most use cases! 

Hope you release this soon in Nuxt 🌸 Thank you!
