### ISSUE TITLE
getting random 404s

### ISSUE THREAD

**Issue by juliusmarminge** [unjs/h3#628]
### Environment

- Node.js 20.11
- h3 1.10.0
- listhen 1.5.6

### Reproduction

https://github.com/pingdotgg/uploadthing/tree/h3-debug
https://github.com/pingdotgg/uploadthing/blob/h3-debug/examples/backend-adapters/server/src/h3.ts

### Describe the bug

I have noticed a random 404 error when fetching from itself, i.e. `/api/uploadthing` fetches `/api/uploadthing` on the same server. We use this for our dev webhook but it seems to fails for some reason...

To reproduce, checkout the repo and the linked branch, `pnpm i`, `pnpm build`, `cd examples/backend-adapters` and run the h3 example using `pnpm dev:h3`. This starts a vite server up at port 5173 as well as a listhen instance on port 3000 with the h3 app.

Attempt to upload an image, and wait for the 404 to show up.

I also added a [simple nitro](https://github.com/pingdotgg/uploadthing/tree/h3-debug/examples/backend-adapters/server/routes/api) server that you can compare to (run using `pnpm dev:nitro`), which works out of the box without issues. Maybe I have configured the h3 app wrong?

### Additional context

I also tried using a "raw" node.js server to eliminate listhen as the possible cause of error but that had the same behavior

### Running the h3 app

https://github.com/unjs/h3/assets/51714798/64238aa1-c465-4915-b3e2-880d4e3f8f81

### Running Nitro for comparison

https://github.com/unjs/h3/assets/51714798/4c1a933a-c9f0-4d0e-be3c-f0a62f38214b

**Comment by pi0** [comment]
Hi, dear @juliusmarminge. First, THANK YOU for spending time to make proper reproduction and write description and nice work in `uploadthing` library ❤️ 

I have did little investigation to find a simple fix!

Some more context: 

H3 router by default is in non-preemptive mode (see https://github.com/unjs/h3/pull/194 and https://github.com/unjs/h3/issues/183 -- it is to allow multiple routers) but in Nitro, the router is preemptive because we can safely assume it for top-level router (https://github.com/unjs/nitro/pull/1504). When router is in non-preemptive mode and an event handler returns an `undefined` value (the issue in uploadthing), h3 keep search other middleware (which non of them also response) and finally give a 404 back.
